### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by Dbrowne1102** [DigitME2/oee_server#21]
HI,

Is there another option for login, i am having difficulty being able to login once the download is complete

**Comment by Samba89** [comment]
Hi, I'd be happy to help you fix this if you can give more information.

I assume you have run the installation script. Have you opened a browser and accessed "localhost" ?

**Comment by Dbrowne1102** [comment]
HI Sam,

Apologies on the late reply,

A colleague of mine let me borrow a spare PC and was able to install ubuntu
22.4 again and was able to get it too work! So must have been an issue with
my Ubuntu download,


Thank you for your time and effort,

Kind regards,
D
